PM4 Update
poggit-orphanage/ItemCase pull request #10
Opened 2022-08-27 10:18 UTC by ItsToxicGG

2022-08-27 10:19 UTC, ItsToxicGG commented
NEEDS TO BE TESTED

2022-08-28 01:27 UTC, SOF3 requested changes

2022-08-28 01:27 UTC, SOF3 commented on src/aliuly/itemcasepe/Main.php
> +            $world = $this->getServer()->getWorldManager()->getWorld();
are you sure this is correct?

2022-08-28 01:27 UTC, SOF3 commented on src/aliuly/itemcasepe/Main.php
> +            $world = $this->getServer()->getWorldManager()->getWorld();
same here

2022-08-28 01:27 UTC, SOF3 commented on src/aliuly/itemcasepe/Main.php
> +        $world = $level->getWorld();
why?

2022-08-28 01:27 UTC, SOF3 commented on src/aliuly/itemcasepe/Main.php
> +        $world = $lv->getWorldManager()->getWorldByName;
... please check

2022-08-28 01:27 UTC, SOF3 commented on src/aliuly/itemcasepe/Main.php
> +        $world = $lv->getWorld();
same here, should be folder name instead?

2022-08-28 01:27 UTC, SOF3 commented on src/aliuly/itemcasepe/Main.php
> +        $world = $level->getWorld();
same gere

2022-08-28 01:27 UTC, SOF3 commented on src/aliuly/itemcasepe/Main.php
>          $world = $level->getName();
did you forget to change this

2022-08-28 01:27 UTC, SOF3 commented on src/aliuly/itemcasepe/Main.php
> +        $pk->metadata = [\pocketmine\network\mcpe\protocol\types\entity\EntityMetadataProperties::FLAGS => [\pocketmine\network\mcpe\protocol\types\entity\EntityMetadataTypes::LONG, 1 << \pocketmine\
why don't you import the class?

2022-08-28 01:27 UTC, SOF3 commented on src/aliuly/itemcasepe/Main.php
> +        $world = $level->getWorld();
same here

2022-08-28 01:27 UTC, SOF3 commented on src/aliuly/itemcasepe/Main.php
> +        $world = $e->getWorld()->getName();
change to folder name

2022-08-28 01:27 UTC, SOF3 commented on src/aliuly/itemcasepe/Main.php
>          if (!isset($this->cases[$level->getName()])) return;
change to folder name

2022-08-28 01:27 UTC, SOF3 commented on src/aliuly/itemcasepe/Main.php
> +                if ($bl->getID() == \pocketmine\block\BlockLegacyIds::STONE_SLAB) {
import the class

2022-08-28 01:27 UTC, SOF3 commented on src/aliuly/itemcasepe/Main.php
> +        if ($item->getId() === \pocketmine\item\ItemIds::AIR) {
import the class

2022-08-28 01:27 UTC, SOF3 commented on src/aliuly/itemcasepe/Main.php
>          $cid = implode(":", [$bl->getX(), $bl->getY() + $yoff, $bl->getZ()]);
import

2022-09-04 11:34 UTC, SOF3 commented
you're just adding random files at this point. seeing no reply to the aforementioned issues I'm closing this PR.

2022-09-04 11:34 UTC, closed without merging

2022-09-04 12:20 UTC, ItsToxicGG commented
True im out of idea I'm gonna fix it with 0 lints

2022-09-04 13:21 UTC, SOF3 commented
Please stick to the topic. If your PR is about updating for PM4, please don't include changes that are not related to updating for PM4.

2022-09-04 13:21 UTC, SOF3 commented
What does `WorldC.php` even do?